CREATE TABLE snake_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    score INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE snake_scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to insert their own score"
ON snake_scores
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow all users to view scores"
ON snake_scores
FOR SELECT
TO anON, authenticated
USING (true);
